name: stellar_wallet_v3
description: Stellar Wallet App for Android and iOS.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  font_awesome_flutter: ^6.0.0
  google_sign_in: ^3.0.3
  firebase_auth: ^0.5.9
  firebase_database: ^0.4.6
  firebase_messaging: ^0.2.5
  firebase_storage: ^0.3.4
  firebase_remote_config: ^0.0.2
  shared_preferences: ^0.4.0
  path_provider: ^0.4.0
  qr_flutter: ^1.0.0
  audioplayer: ^0.4.0
  image_picker: ^0.3.1
  device_info: any
  latlong: ^0.4.5
  json_annotation: ^0.2.3
  decimal: ^0.1.3
  zxing: ^0.0.4+1
  flutter_string_encryption: "^0.0.2"

#  barcodescanner:
#      #this will be replaced with a proper dependency, once the plugin is release to dart-pub
#      git: https://github.com/swissonid/BarcodeScannerPlugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_style: ^1.0.10
  build_runner: ^0.8.0
  json_serializable: ^0.5.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
        - assets/wallet1.png
        - assets/wallet2.png
        - assets/panther.png
        - assets/girl.png
        - assets/coins.mp3
        - assets/flyby.mp3
        - assets/glass.mp3
        - assets/pin.mp3
        - assets/ting.mp3
        - assets/drama.mp3

  fonts:
      - family: Raleway
        fonts:
          - asset: fonts/Raleway-Regular.ttf
          - asset: fonts/Raleway-Italic.ttf
          - asset: fonts/Raleway-ExtraBold.ttf
          - asset: fonts/Raleway-Bold.ttf
      - family: RobotoMono
        fonts:
          - asset: fonts/Roboto-Regular.ttf
          - asset: fonts/Roboto-Bold.ttf